# Generated by Django 5.0.2 on 2024-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='session',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('music', 'Music'), ('dance', 'Dance'), ('games', 'Games')], max_length=20, null=True),
        ),
    ]
